[tool.briefcase]
project_name = "Mint Deck"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/mintdeck"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'Alexander Kettler'
author_email = "alexander@example.com"

[tool.briefcase.app.mintdeck]
formal_name = "Mint Deck"
description = "Podcast desktop player"
icon = "src/mintdeck/resources/mintdeck"
sources = ['src/mintdeck']
requires = []


[tool.briefcase.app.mintdeck.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.mintdeck.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.mintdeck.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.mintdeck.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.mintdeck.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
